//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpCutCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpCutCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built on: .
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG (*.png)|*.png.
        /// </summary>
        public static string CaptureFrameFormatFilter {
            get {
                return ResourceManager.GetString("CaptureFrameFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (error!).
        /// </summary>
        public static string ChangelogError {
            get {
                return ResourceManager.GetString("ChangelogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been using SharpCut for a while now, thank you! Would you like to visit the author&apos;s website? :).
        /// </summary>
        public static string Courtesy {
            get {
                return ResourceManager.GetString("Courtesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok! I won&apos;t bother you with this again. Enjoy SharpCut!.
        /// </summary>
        public static string CourtesyDisabled {
            get {
                return ResourceManager.GetString("CourtesyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using SharpCut!.
        /// </summary>
        public static string CourtesyTitle {
            get {
                return ResourceManager.GetString("CourtesyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-Separated Values (*.csv)|*.csv.
        /// </summary>
        public static string CsvFilter {
            get {
                return ResourceManager.GetString("CsvFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_save {
            get {
                object obj = ResourceManager.GetObject("document-save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to download the file. Check your network connection..
        /// </summary>
        public static string DownloadFileError {
            get {
                return ResourceManager.GetString("DownloadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remux to the same container..
        /// </summary>
        public static string ErrorCannotRemuxToSource {
            get {
                return ResourceManager.GetString("ErrorCannotRemuxToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one cut section before you can export media..
        /// </summary>
        public static string ErrorCutSectionsRequiredBeforeExport {
            get {
                return ResourceManager.GetString("ErrorCutSectionsRequiredBeforeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file format is not supported by SharpCut..
        /// </summary>
        public static string ErrorFormatNotSupported {
            get {
                return ResourceManager.GetString("ErrorFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed opening a SharpCut/LosslessCut project..
        /// </summary>
        public static string ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the video file. Perhaps the file is locked by another application?.
        /// </summary>
        public static string ErrorLoadingVideo {
            get {
                return ResourceManager.GetString("ErrorLoadingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video loading/playback error occurred.
        ///Check your system configuration..
        /// </summary>
        public static string ErrorMediaPlayer {
            get {
                return ResourceManager.GetString("ErrorMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting cut segments....
        /// </summary>
        public static string ExportingSections {
            get {
                return ResourceManager.GetString("ExportingSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube chapters have been exported to your clipboard.
        ///Please paste the contents into the description field of your video..
        /// </summary>
        public static string ExportToYoutubeTimestampsMessage {
            get {
                return ResourceManager.GetString("ExportToYoutubeTimestampsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string ExportToYoutubeTimestampsMessageTitle {
            get {
                return ResourceManager.GetString("ExportToYoutubeTimestampsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have provided an invalid file name template.
        ///File name templates must contain at least 1 character and can contain the following variables:
        ///- $(OriginalFn)
        ///- $(SegStart)
        ///- $(SegEnd)
        ///- $(Timestamp)
        ///- $(Ext).
        /// </summary>
        public static string FileNameTemplateInvalid {
            get {
                return ResourceManager.GetString("FileNameTemplateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name template.
        /// </summary>
        public static string FileNameTemplateInvalidTitle {
            get {
                return ResourceManager.GetString("FileNameTemplateInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating timeline preview....
        /// </summary>
        public static string GeneratingPreviewFrames {
            get {
                return ResourceManager.GetString("GeneratingPreviewFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string GenericErrorTitle {
            get {
                return ResourceManager.GetString("GenericErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string GenericPleaseWait {
            get {
                return ResourceManager.GetString("GenericPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_first {
            get {
                object obj = ResourceManager.GetObject("go-first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_last {
            get {
                object obj = ResourceManager.GetObject("go-last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_add {
            get {
                object obj = ResourceManager.GetObject("list-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_remove {
            get {
                object obj = ResourceManager.GetObject("list-remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File merge has been completed. Would you like to open the resulting file in SharpCut?.
        /// </summary>
        public static string MergeComplete {
            get {
                return ResourceManager.GetString("MergeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge completed.
        /// </summary>
        public static string MergeCompleteTitle {
            get {
                return ResourceManager.GetString("MergeCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging files....
        /// </summary>
        public static string MergingFiles {
            get {
                return ResourceManager.GetString("MergingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tried to load multiple files into SharpCut. Would you like to merge them?.
        /// </summary>
        public static string MultipleFilesMerge {
            get {
                return ResourceManager.GetString("MultipleFilesMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files provided.
        /// </summary>
        public static string MultipleFilesMergeTitle {
            get {
                return ResourceManager.GetString("MultipleFilesMergeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of SharpCut available. It is highly recommended to install the latest version, as it brings many improvements and fixes for known bugs. Would you like to install the update now?.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available. You are running the latest version..
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string ProgressPercent {
            get {
                return ResourceManager.GetString("ProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to export one of the video segments, if you can - please take a screenshot of this message and report it to the developer:
        ///%e.
        /// </summary>
        public static string ProjectExportError {
            get {
                return ResourceManager.GetString("ProjectExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export video segments.
        /// </summary>
        public static string ProjectExportErrorTitle {
            get {
                return ResourceManager.GetString("ProjectExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpCut/LosslessCut Project (.llc)|*.llc.
        /// </summary>
        public static string ProjectFormatFilter {
            get {
                return ResourceManager.GetString("ProjectFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to merge video segments, if you can - please take a screenshot of this message and report it to the developer:
        ///%e.
        /// </summary>
        public static string ProjectMergeError {
            get {
                return ResourceManager.GetString("ProjectMergeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to merge video segments.
        /// </summary>
        public static string ProjectMergeErrorTitle {
            get {
                return ResourceManager.GetString("ProjectMergeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when trying to remux the video, if you can - please take a screenshot of this message and report it to the developer:
        ///%e.
        /// </summary>
        public static string ProjectRemuxError {
            get {
                return ResourceManager.GetString("ProjectRemuxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remux the video.
        /// </summary>
        public static string ProjectRemuxErrorTitle {
            get {
                return ResourceManager.GetString("ProjectRemuxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remuxing files....
        /// </summary>
        public static string RemuxingFiles {
            get {
                return ResourceManager.GetString("RemuxingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameSectionFormTitle {
            get {
                return ResourceManager.GetString("RenameSectionFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section name.
        /// </summary>
        public static string RenameSectionLabel {
            get {
                return ResourceManager.GetString("RenameSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename section.
        /// </summary>
        public static string RenameSectionTitle {
            get {
                return ResourceManager.GetString("RenameSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string SecondIndicator {
            get {
                return ResourceManager.GetString("SecondIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        public static string SectionDuration {
            get {
                return ResourceManager.GetString("SectionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SectionSelected {
            get {
                return ResourceManager.GetString("SectionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string SectionTotal {
            get {
                return ResourceManager.GetString("SectionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection.
        /// </summary>
        public static string SelectionLabelNoSelection {
            get {
                return ResourceManager.GetString("SelectionLabelNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string SelectionLabelProjectNotOpen {
            get {
                return ResourceManager.GetString("SelectionLabelProjectNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SharpCutSmall {
            get {
                object obj = ResourceManager.GetObject("SharpCutSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://conflagrate.co/software/sharpcut/manifest.beta.json.
        /// </summary>
        public static string UpdateBetaManifestURL {
            get {
                return ResourceManager.GetString("UpdateBetaManifestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://conflagrate.co/software/sharpcut/changelog.txt.
        /// </summary>
        public static string UpdateChangelogURL {
            get {
                return ResourceManager.GetString("UpdateChangelogURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while downloading the update..
        /// </summary>
        public static string UpdateDownloadError {
            get {
                return ResourceManager.GetString("UpdateDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://conflagrate.co/software/sharpcut/manifest.json.
        /// </summary>
        public static string UpdateManifestURL {
            get {
                return ResourceManager.GetString("UpdateManifestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap video_x_generic {
            get {
                object obj = ResourceManager.GetObject("video-x-generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
